### ISSUE TITLE
How to make nss operator to watch operator created in other namespace

### ISSUE THREAD

**Issue by robin2008** [IBM/ibm-namespace-scope-operator#95]
I have nss operator installed in namespace A, and it could projects my application operator role and rolebinding to my targeted namespace B successfully when my operator is in namespace A.

While I create my operator (w/ OLM) in namespace C, then the role/rolebinding projecting to B does not work.

Any possible configuration is required to make this work?

**Comment by Daniel-Fan** [comment]
Hi @robin2008 

The NSS operator is namespaced-scoped. in other words, the nss operator installed in namespace A will only manage the permission projection for the operators in namespace A.

Therefore, if you want to extend the permission of operators in another namespace C, we need to install an additional nss operator in namespace C.

Hope this would be helpful!

![image](https://user-images.githubusercontent.com/29827416/119908078-c3838580-bf1f-11eb-8732-86bd277b7a24.png)

**Comment by robin2008** [comment]
@Daniel-Fan 
Thank you for the information. This is clear and I can install another nss operator to meet my needs.
